#!/bin/bash

INPUT_DIR=$1
INPUT_NAME=$2
OUTPUT_DIR=$3
ROOT_DIR=$4
shift 4
SYSTEM_TAGS="${@}"

OUT_FILE=$OUTPUT_DIR/.$INPUT_NAME.symlink

$ROOT_DIR/tools/cat-append.sh $INPUT_DIR $ROOT_DIR $SYSTEM_TAGS > $OUT_FILE
